@base = http://localhost:5000

### 🧍‍♀️ Login (Required First)
# @name login
POST {{base}}/api/auth/login
Content-Type: application/json

{
  "email": "soumyatest@example.com",
  "password": "mypassword123"
}


### ➕ Add Grocery
POST {{base}}/api/groceries
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Apples",
  "quantity": 5,
  "price": 100
}


### 📋 Get All Groceries
GET {{base}}/api/groceries
Authorization: Bearer {{login.response.body.token}}


### ✏️ Update Grocery
# Replace {{grocery_id_here}} with actual _id from Get request
PUT {{base}}/api/groceries/6740c1a2b1aabc1234d9ef56
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "name": "Bananas",
  "quantity": 10,
  "price": 120
}


### ❌ Delete Grocery
# Replace {{grocery_id_here}} with actual _id from Get request
DELETE {{base}}/api/groceries/6740c1a2b1aabc1234d9ef56
Authorization: Bearer {{login.response.body.token}}
